### ISSUE TITLE
Back to spicetify default theme

### ISSUE THREAD

**Issue by Irrelevance-Syv** [khanhas/google-spicetify#3]
What do I've to do to go back from google spicetify themes to default spicetify themes? Google spicetify themes are beautiful but still the green spicetify theme is the best one for me.
I've tried spicetify config current_theme 'default, spicetifydefault etc.' but none of them worked for me

**Comment by khanhas** [comment]
Did you run apply after you changed the config?

**Comment by Irrelevance-Syv** [comment]
I did but somehow i corrupted my theme files while i was doing it first time. I redo everthing and now it works. I can switch between google spicetify and spicetify default themes. Ty for everthing
